title: Sameera Kapila
timezone: America/Chicago
collections:
  clips:
    title: Clips
    output: true
    permalink: clips/:year/:month/:day/:title
    layout: clip
  food:
    title: Food
    output: true
    permalink: food/:year/:month/:day/:title
  posts:
    title: Posts
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
description: Sameera Kapila is a product designer, speaker, writer, and educator based in Austin. She is a Design Director at thoughtbot and always cooking.
baseurl:
url: https://samkapila.com
twitter_username: samkap
github_username: samkap
markdown: kramdown
kramdown:
  parse_block_html: true
  gfm_quirks: paragraph_end
  html_to_native: false
theme: minima
sass:
  style: compressed
plugins:
  - bourbon
  - jekyll-twitter-plugin
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
date_format: "%b %-d, %Y"
logo-image: "/img/ampersam.svg"
nav-breaking-point: 520px
sitemap:
  filename: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
    - "/clips/index.md"
  change_frequency_name: change_frequency
  priority_name: priority
github:
  repo: samkap/samkap.github.io
  branch: master
pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
